Google Authentication Functions
cornell-dti/carriage-ios pull request #7
Opened 2019-11-14 17:04 UTC by bethmiecz

The functions needed for Google authentication were added to AppDelegate. I am currently working on finish the profile and then sign-up pages, which will have a Google sign-in button added to them that uses the output of these functions to determine name, email, id.

2019-11-15 14:47 UTC, lsizemore8 reviewed
Generally this looks good to me, but let's not merge this in until we connect backend & get the client ID in, it doesn't seem worthwhile to merge non-finished code to master. If we're finding that both of you need this on master to continue on, we'll reconsider.

2019-11-15 14:54 UTC, lsizemore8 requested changes
My bad, did just notice this issue. Add the line I commented/make sure that doesn't break anything. If it doesn't, then I believe the only thing we're waiting on would be backend and us setting up a client ID

2019-11-15 14:54 UTC, lsizemore8 commented on carriage-user-ios/carriage-user-ios/AppDelegate.swift
> +        GIDSignIn.sharedInstance().delegate = self
Add in GIDSignIn.sharedInstance().hostedDomain = "cornell.edu" so we can limit the sign in to cornell emails only :)

2019-11-19 22:37 UTC, bethmiecz commented
WIP: still need client id from backend (currently has one I generated to prove that the functionality works)

2020-02-11 22:31 UTC, closed without merging